name: Docker Nexus
on:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image using Buildx
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: myimage:latest

      - name: Build Docker image using Docker build
        run: docker build -t myimage:latest .

      - name: Login to Nexus Repository
        uses: docker/login-action@v1
        with:
          registry: 8083-nexus-tecdmwng.ldapowner.opsera.io
          username: admin
          password: XlQM2gXFC9

      - name: Tag and Push Docker image to Nexus Repository
        run: |
          docker tag myimage:latest 8083-nexus-tecdmwng.ldapowner.opsera.io/docker-repo:myimage-latest
          docker push 8083-nexus-tecdmwng.ldapowner.opsera.io/docker-repo:myimage-latest
